export const RELIGIONS = [
  "Hindu",
  "Sikh",
  "Jain",
  "Muslim",
  "Christian",
  "Buddhist",
  "Parsi",
  "Jewish",
  "Spiritual - No Religion",
  "Other",
];

export const COMMUNITIES_BY_RELIGION: Record<string, string[]> = {
  Hindu: [
    "All Hindu Communities",
    "Agarwal / Aggarwal",
    "Brahmin - Gaur",
    "Brahmin - Saraswat",
    "Brahmin - Kanyakubja",
    "Brahmin - Sanadhya",
    "Brahmin - Maithil",
    "Brahmin - Nagar",
    "Brahmin - Other",
    "Jat",
    "Gujjar / Gurjar",
    "Yadav / Ahir",
    "Rajput",
    "Punjabi / Khatri",
    "Punjabi / Arora",
    "Punjabi / Bhatia",
    "Gupta",
    "Maheshwari",
    "Khandelwal",
    "Baniya / Vaishya",
    "Maratha / Kunbi",
    "Kayastha",
    "Kurmi / Patel / Patidar",
    "Saini / Mali",
    "Reddy",
    "Naidu",
    "Kamma",
    "Nair",
    "Ezhava",
    "Lingayat",
    "Vanniyar",
    "Thevar",
    "Gounder",
    "Bishnoi",
    "Sindhi",
    "Kashmiri Pandit",
    "Meena",
    "Koli",
    "Teli",
    "Vishwakarma / Dhiman",
    "Kamboj",
    "Ror",
    "Scheduled Caste (SC)",
    "Scheduled Tribe (ST)",
    "Other Backward Class (OBC)",
    "Hindu - Other / Open to All",
  ],
  Sikh: [
    "All Sikh Communities",
    "Jat Sikh",
    "Khatri / Arora Sikh",
    "Ramgarhia",
    "Gursikh / Amritdhari",
    "Saini Sikh",
    "Ahluwalia",
    "Mazhabi Sikh",
    "Ravidasia Sikh",
    "Bhatra Sikh",
    "Kamboj Sikh",
    "Sikh - Other / Open to All",
  ],
  Jain: [
    "All Jain Communities",
    "Digambar - Agarwal",
    "Digambar - Khandelwal",
    "Digambar - Porwal",
    "Digambar - Other",
    "Shwetambar - Oswal",
    "Shwetambar - Murti Pujak",
    "Shwetambar - Sthanakvasi",
    "Shwetambar - Terapanthi",
    "Shwetambar - Other",
    "Jain - Open to All",
  ],
  Muslim: [
    "All Muslim Communities",
    "Sunni - Ansari",
    "Sunni - Khan / Pathan",
    "Sunni - Syed",
    "Sunni - Sheikh",
    "Sunni - Qureshi",
    "Sunni - Malik",
    "Sunni - Mughal",
    "Shia - Syed",
    "Shia - Other",
    "Bohra",
    "Khoja",
    "Muslim - Other / Open to All",
  ],
  Christian: [
    "All Christian Communities",
    "Catholic - Roman Catholic",
    "Catholic - Latin Catholic",
    "Catholic - Syro Malabar",
    "Protestant",
    "Orthodox - Syrian Orthodox",
    "Orthodox - Jacobite",
    "Born Again / Pentecostal",
    "Christian - Other / Open to All",
  ],
  Buddhist: [
    "All Buddhist Communities",
    "Mahayana",
    "Theravada",
    "Navayana / Neo-Buddhist",
    "Buddhist - Other",
  ],
  Parsi: [
    "All Parsi Communities",
    "Irani",
    "Parsi - Zoroastrian",
    "Parsi - Other",
  ],
  Jewish: [
    "All Jewish Communities",
    "Bene Israel",
    "Baghdadi",
    "Cochin Jewish",
    "Jewish - Other",
  ],
};

// Flattened popular community options for quick search when no religion is selected
export const POPULAR_COMMUNITIES = [
  "All Communities",
  "Agarwal / Aggarwal",
  "Brahmin - All",
  "Jat",
  "Gujjar / Gurjar",
  "Yadav / Ahir",
  "Rajput",
  "Punjabi / Khatri",
  "Punjabi / Arora",
  "Jat Sikh",
  "Gupta",
  "Maheshwari",
  "Khandelwal",
  "Jain - All",
  "Maratha",
  "Kayastha",
  "Patel / Patidar",
  "Saini / Mali",
  "Baniya / Vaishya",
  "Sindhi",
  "Other / Open to All",
];

// Helper to get communities specifically for a chosen religion
export function getCommunitiesForReligion(religion?: string): string[] {
  if (!religion || religion === "All" || religion === "Other" || religion === "Spiritual - No Religion") {
    return POPULAR_COMMUNITIES;
  }
  return COMMUNITIES_BY_RELIGION[religion] || ["Other / Open to All"];
}

// All flat castes list for select inputs
export const ALL_CASTES_LIST = Object.values(COMMUNITIES_BY_RELIGION).flat();
